# Don't print a new line at the start of the prompt
add_newline = false

# Battery symbols
[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

# Show battery at certain thresholds
[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]  
threshold = 30
style = "bold yellow"

# Custom error symbol
[character]
success_symbol = "[â¯](bold green)" 
error_symbol = "[âœ—](bold red) "

[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = "%I:%M"
utc_time_offset = "-5"
# time_range = "10:00:00-14:00:00"
